name: project-euler
version: '0.1.0.0'
category: Web
author: Anup Kishore
maintainer: anup@secondspectrum.com
copyright: 2017 Anup Kishore
license: BSD3
github: anup-2s/project-euler
extra-source-files:
- README.md
library:
  source-dirs:
  - src
  exposed-modules:
  - Lib
  dependencies:
  - base >=4.7 && <5
executables:
  project-euler-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - project-euler
tests:
  project-euler-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - project-euler
